version: '3.7'

services:
  web:
    build:
      context: ./app
      dockerfile: Dockerfile.prod
    image: warpig69/recipes-backend
    command: gunicorn recipes_rest.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/home/app/web/staticfiles
    expose:
      - 8000
    env_file:
      - ./.env.prod
    depends_on:
      - db
    networks:
      - testnetwork
  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.prod.db
    networks:
      - testnetwork

  nginx:
    image: warpig69/nginx
    build: ./nginx
    ports:
      - 80:80
    volumes:
      - static_volume:/home/app/web/staticfiles
    depends_on:
      - web
    networks:
      - testnetwork

volumes:
  postgres_data:
  static_volume:

networks:
  testnetwork:
    external: true
