version: '3.7'

services:
  db:
    image: library/postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=hello_django
      - POSTGRES_PASSWORD=hello_django
      - POSTGRES_DB=hello_django_dev
    networks:
      - testnetwork
  web:
    image: warpig69/recipes-backend
    build: ./app
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./app/:/usr/src/app/
    env_file:
      - ./.env.dev
    ports:
      - "8000:8000"
    networks:
      - testnetwork

volumes:
  postgres_data:

networks:
  testnetwork:
    external: true