# Generated by Django 3.0.5 on 2020-04-15 17:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chef',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('url', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='IngredientsSegment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=4000)),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=500)),
                ('preparation_time', models.IntegerField(null=True)),
                ('cooking_time', models.IntegerField(null=True)),
                ('preparation_time_text', models.CharField(max_length=100, null=True)),
                ('cooking_time_text', models.CharField(max_length=100, null=True)),
                ('description', models.CharField(max_length=4000, null=True)),
                ('added_at', models.DateTimeField(auto_now=True)),
                ('chefs', models.ManyToManyField(to='backend.Chef')),
                ('ingredients', models.ManyToManyField(to='backend.Ingredient')),
            ],
        ),
        migrations.CreateModel(
            name='MealIngredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingredient_and_amount_text', models.CharField(max_length=300)),
                ('ingredient_segment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.IngredientsSegment')),
            ],
        ),
        migrations.AddField(
            model_name='ingredientssegment',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.Recipe'),
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=1000)),
                ('url', models.CharField(max_length=500)),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.Recipe')),
            ],
        ),
    ]
